name: Preview or update Pulumi app GS1_DIGITAL_LINK_RESOLVER
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Pulumi CLI
        run: |
          curl -fsSL https://get.pulumi.com | sh
          export PATH=$PATH:/root/.pulumi/bin

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          aws-role-session-name: ${{ secrets.AWS_ROLE_SESSION_NAME }}
          aws-region: ap-southeast-2

      - name: Pulumi Login
        run: pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Pulumi Preview
        run: |
          echo "${{ secrets.INFRASTRUCTURE_ENV }}" > infrastructure/.env
          pulumi preview
        working-directory: infrastructure

      - name: Pulumi Deploy
        run: |
          echo "${{ secrets.INFRASTRUCTURE_ENV }}" > infrastructure/.env
          pulumi up --yes
        working-directory: infrastructure
